version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:7
    steps:
      - checkout
      - run:
          name: Install project dependencies
          command: npm install
      - run:
          name: Install the latest version of eslint
          command: npm install -g eslint
      - run:
          name: Run eslint
          command: eslint .
      - run:
          name: Run test suite
          command: npm test
